name: Push Tag

on:
  push:
   
jobs:
  push_tag:
    name: Push Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git and generate tag
        run: |
          git config --global user.email "oki.maureen.eloho@gmail.com"
          git config --global user.name "okimaureen"
          export GITHUB_TOKEN=${{ secrets.PAT }}
          NEXT_VERSION=$(chronicle next-version)
          git tag -a ${NEXT_VERSION} -m "New version ${NEXT_VERSION}"
          

      - name: Push Tag
        run: git push origin --tags
