name: jira

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review
      - edited
      - reopened

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set GitHub Summary
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
        shell: bash
   
      - name: Set GitHub Path
        run: |
          echo "Hello there" >> "$GITHUB_STEP_SUMMARY"
        shell: bash

      - name: Set GitHub Path
        run: |
          echo "Hello my" >> "$GITHUB_STEP_SUMMARY"
        shell: bash
      # - name: run action
      #   uses: ./.github/actions/summary
