name: Tags
on:
  push:

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world'

  hello-world2:
    name: Hello world  renewed
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world renewed'
