name: "simple tag"
run-name: "simple tag"

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world update'
